### PR TITLE
GH-455 fix license checking

### LINKED ISSUE #455: License check failing for 'Commercial' type in 6.6.1
**Describe the bug**
Since version 6.6.1 of the provider we've been getting the following error when `check_license = true`:
```
$ terraform plan
╷
│ Error: Artifactory Projects requires Enterprise license to work with Terraform!
│
│   with provider["registry.terraform.io/jfrog/artifactory"],
│   on main.tf line 10, in provider "artifactory":
│   10: provider "artifactory" {
│
```

Our license is `Commercial`:
```
$ curl -H "Authorization: Bearer $ARTIFACTORY_ACCESS_TOKEN" https://<host>/artifactory/api/system/license
{
  "type" : "Commercial",
  "validThrough" : "EXPIRY",
  "licensedTo" : "ORG"
}
```

Looks like this is down to switching to the check licenses function in `terraform-provider-shared`:
- https://github.com/jfrog/terraform-provider-artifactory/blob/bd2f0390f83ed4d926635b8f852cf60644ef457e/pkg/artifactory/provider/provider.go#L239
- https://github.com/jfrog/terraform-provider-shared/blob/v0.5.0/util/util.go#L344

Obviously we can set `check_license = false` but I'd like to confirm that this is expected behaviour (i.e the license check should be excluding `Commercial` now). I wouldn't expect a breaking change like this in a patch release.

**Expected behavior**
I wouldn't necessarily expect an error when this worked previously. Especially when bumping a patch version from 6.6.0 to 6.6.1.

**Additional context**

Some information:
- Artifactory version: 7.35.2
- Terraform provider version: 6.6.1
- Terraform version: 1.1.9

### PR DESCRIPTION
**Pull request by alexhung**
Fixes #455

Uses updated `CheckArtifactoryLicense()` in https://github.com/jfrog/terraform-provider-shared/pull/11

Tested through using Charles' rewrite feature and overwrite the API response to contain either `Enterprise`, `Commercial`, or `Edge` license type in the payload.

### CODE REVIEW

**Comment by alexhung** [comment]
@chb0github ☝🏼

File: pkg/artifactory/provider/provider.go [hunk 1]
```diff
@@ -196,7 +196,7 @@ func providerConfigure(ctx context.Context, d *schema.ResourceData, terraformVer
 
 	checkLicense := d.Get("check_license").(bool)
 	if checkLicense {
-		licenseErr := util.CheckArtifactoryLicense(restyBase)
```
Comment (chb0github) [inline pkg/artifactory/provider/provider.go:199]: I am really starting to feel like some extension are in order. More like:

```go
  utils.InSlice(client.GetLicense(), "Enterprise","Commercial", "Edge"))
```

**Review by chb0github — APPROVED** [review]

File: pkg/artifactory/provider/provider.go (hunk 1 above)
Comment (alexhung) [reply pkg/artifactory/provider/provider.go:199]: Good idea. I'll write up a ticket for this 😄  In the meantime, let's get this one out first.

**Review by maheshjfrog — APPROVED** [review]

**Review by danielmkn — APPROVED** [review]

File: pkg/artifactory/provider/provider.go (hunk 1 above)
Comment (alexhung) [reply pkg/artifactory/provider/provider.go:199]: With Go 1.18 one can do `slices.Contains([]string{"Enterprise", "Commercial", "Edge"}, client.GetLicense())`
