### PR TITLE
GH-370 fix max unique tags does not reset

### LINKED ISSUE #370: max_unique_tags doesn't take effect when set to 0
**Describe the bug**
We are using Artifactory 7.33.12 and terraform module 2.25.0.
According to the [documentation](https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/artifactory_local_docker_v2_repository), setting ***max_unique_tags*** to 0 allows unlimited tags. However, when setting it to 0 in terraform, the actually applied value is 5, which is the default value I believe.

I have also verified that values other than 0 will take effect.

Below is the resource definition we used
```

resource "artifactory_local_docker_v2_repository" "test_docker_dev_local" {
  key             = "test-docker-dev-local"
  tag_retention   = 3
  max_unique_tags = 0
  repo_layout_ref = "simple-default"
  property_sets   = ["artifactory"]
}
```

Thank you in advance for any help!

**Requirements for and issue**
- [x] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue): see above
- [x] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`:  7.33.12
- [x] Your version of terraform:  2.25.0

**Expected behavior**
The actual **Max Unique Tags** should be set to 0 when 0 is configured in terraform module.

**Additional context**

### PR DESCRIPTION
**Pull request by alexhung**
Fixes #370

- Fix `max_unique_tags` ignores 0 value
- Add default value (0) to the same

### CODE REVIEW

**Review by maheshjfrog — APPROVED** [review]

**Review by dasmanas — DISMISSED** [review]

**Review by chb0github — APPROVED** [review]

File: pkg/artifactory/resource_artifactory_local_docker_repository.go [hunk 1]
```diff
@@ -127,7 +127,7 @@ func resourceArtifactoryLocalDockerV1Repository() *schema.Resource {
 
 type DockerLocalRepositoryParams struct {
 	LocalRepositoryBaseParams
-	MaxUniqueTags       int    `hcl:"max_unique_tags" json:"maxUniqueTags,omitempty"`
+	MaxUniqueTags       int    `hcl:"max_unique_tags" json:"maxUniqueTags"`
```
Comment (chb0github) [inline pkg/artifactory/resource_artifactory_local_docker_repository.go:130]: fyi: you don't need the `hcl` anymore.

**Review by chb0github — APPROVED** [review]

File: pkg/artifactory/resource_artifactory_local_docker_repository.go (hunk 1 above)
Comment (alexhung) [reply pkg/artifactory/resource_artifactory_local_docker_repository.go:130]: ahhh, good point. Next time!
