### PR TITLE
GH-705 update repository environments attribute limit

### LINKED ISSUE #705: Update repository's `project_environments` constraint to allow only 1 item
**Describe the bug**

Prior the introduction of custom environment in [Artifactory 7.53.1](https://www.jfrog.com/confluence/display/JFROG/Artifactory+Release+Notes#ArtifactoryReleaseNotes-Artifactory7.53.1Cloud), up to 2 environments can be assigned to attribute `project_environments`. From 7.53.1 onward, only 1 environment can be assigned to repository.

https://www.jfrog.com/confluence/display/JFROG/Environments

**Requirements for and issue**
- [x] A description of the bug
- [ ] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). **If this is not supplied, this issue will likely be closed without any effort expended.**
- [ ] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [ ] Your version of terraform
- [ ] Your version of terraform provider

**Expected behavior**

Provider to restrict attribute `project_environments` to allow only 1 item only.

**Additional context**

### PR DESCRIPTION
**Pull request by alexhung**
Closes #705 

No need for PR for `v6` branch, as this API change occurs *after* 7.49.10.

- Refactor Terraform schema so the common attributes for all repos are shared.
- Refactor provider configuration function to fetch Artifactory version from API. Then store the version string in provider's metadata variable.
- Update all usages of provider's metadata.
- Add validations based on Artifactory version
  - Keep existing validation for <7.53.1
  - Only allow 1 item (of any string) in list >=7.53.1
- Clean up magic strings

### CODE REVIEW

File: pkg/artifactory/resource/security/resource_artifactory_scoped_token.go [hunk 1]
```diff
@@ -3,16 +3,18 @@ package security
...
 	"fmt"
-	"github.com/jfrog/terraform-provider-shared/packer"
-	"github.com/jfrog/terraform-provider-shared/predicate"
 	"net/http"
 	"regexp"
 	"strings"
 
+	"github.com/jfrog/terraform-provider-shared/packer"
+	"github.com/jfrog/terraform-provider-shared/predicate"
+
```
Comment (danielmkn) [inline pkg/artifactory/resource/security/resource_artifactory_scoped_token.go:12]: Please, regroup and sort imports.

**Review by danielmkn — CHANGES_REQUESTED** [review]
A couple of minor changes are required.

File: pkg/artifactory/resource/repository/local/resource_artifactory_local_docker_repository.go [hunk 2]
```diff
@@ -108,12 +108,12 @@ var DockerV1LocalSchema = util.MergeMaps(
 			Computed: true,
 		},
 	},
-	repository.RepoLayoutRefSchema("local", "docker"),
+	repository.RepoLayoutRefSchema(rclass, "docker"),
```
[the remark this answers is not in the document]
Comment (alexhung) [reply pkg/artifactory/resource/repository/local/resource_artifactory_local_docker_repository.go:111]: Good catch! I thought I find them all.

File: pkg/artifactory/resource/security/resource_artifactory_scoped_token.go (hunk 1 above)
Comment (alexhung) [reply pkg/artifactory/resource/security/resource_artifactory_scoped_token.go:12]: hahaha, VSCode failed me.

**Review by danielmkn — APPROVED** [review]
