### PR TITLE
GH-261 Remove omitempty tag for artifactory user resource struct

### LINKED ISSUE #261: `artifactory_user.profile_updatable` shows a change even when unchanged
**Describe the bug**
`profile_updatable` is showing me a change from `true` to `false` when I set it to false in code, even after several applies.

**Requirements for and issue**
- [x] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue)
See the code snippet in https://github.com/jfrog/terraform-provider-artifactory/issues/228

- [x] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
Cloud

- [x] Your version of terraform
1.0.11

**Expected behavior**
Diff reflects actual state and only shows changes when attributes are changed.

**Additional context**
https://github.com/jfrog/terraform-provider-artifactory/issues/228

### PR DESCRIPTION
**Pull request by maheshjfrog**
Fixes #261

### CODE REVIEW

File: pkg/artifactory/resource_artifactory_user.go [hunk 1]
```diff
@@ -10,9 +10,21 @@ import (
 	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
 	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
 	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
-	"github.com/jfrog/jfrog-client-go/artifactory/services"
 )
 
+type User struct {
+	Name                     string   `json:"name,omitempty" csv:"username,omitempty"`
```
Comment (alexhung) [inline pkg/artifactory/resource_artifactory_user.go:16]: Are all these `omitempty` necessary? Why is there `csv` tag as well?

File: pkg/artifactory/resource_artifactory_user.go [hunk 2]
```diff
@@ -42,13 +54,12 @@ func resourceArtifactoryUser() *schema.Resource {
...
 				Description: "When enabled, this user is an administrator with all the ensuing privileges.",
 			},
 			"profile_updatable": {
 				Type:     schema.TypeBool,
 				Optional: true,
-				Computed: true,
+				Default:  true,
 				Description: "When enabled, this user can update their profile details (except for the password. " +
 					"Only an administrator can update the password). There may be cases in which you want to leave " +
 					"this unset to prevent users from updating their profile. For example, a departmental user with " +
```
Comment (alexhung) [inline pkg/artifactory/resource_artifactory_user.go:65]: Please verify the need for `Computed` for the rest of the optional attributes. According to the [API schema](https://www.jfrog.com/confluence/display/JFROG/Security+Configuration+JSON#SecurityConfigurationJSON-application/vnd.org.jfrog.artifactory.security.User+json), they shouldn't be computed at all.

**Review by alexhung — CHANGES_REQUESTED** [review]

File: pkg/artifactory/resource_artifactory_user.go [hunk 3]
```diff
@@ -10,9 +10,21 @@ import (
 	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
 	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
 	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
-	"github.com/jfrog/jfrog-client-go/artifactory/services"
```
Comment (alexhung) [inline pkg/artifactory/resource_artifactory_user.go:13]: I'm kinda surprised that this client is still in the code base. @chb0github

File: pkg/artifactory/resource_artifactory_user.go (hunk 1 above)
Comment (maheshjfrog) [reply pkg/artifactory/resource_artifactory_user.go:16]: omitempty is not necessary. In fact, In this specific attribute ie: profile_updatable it breaks the expected artifactory behavior.

File: pkg/artifactory/resource_artifactory_user.go (hunk 2 above)
Comment (maheshjfrog) [reply pkg/artifactory/resource_artifactory_user.go:65]: Will check for other attributes in this resource. 
I thought, this fix to be point fix for this specific attribute only.

File: pkg/artifactory/resource_artifactory_user.go (hunk 1 above)
Comment (alexhung) [reply pkg/artifactory/resource_artifactory_user.go:16]: Let's remove all unnecessary `omitempty`.

Do we need `csv` tag?

Comment (maheshjfrog) [reply pkg/artifactory/resource_artifactory_user.go:16]: no need for csv tag. will remove them.

Comment (chb0github) [reply pkg/artifactory/resource_artifactory_user.go:16]: csv??? Where did _that_ comes from?!

`omitempty` causes nothing but issues. Definitely remove them and set their default value to what RT would do; then it's super clear in the code the expected behavior

File: pkg/artifactory/resource_artifactory_user.go (hunk 2 above)
Comment (chb0github) [reply pkg/artifactory/resource_artifactory_user.go:65]: I am always leary of expanding scope.

Comment (alexhung) [reply pkg/artifactory/resource_artifactory_user.go:65]: 1. Using `Computed` on those attributes are just wrong. I'm surprised we don't have reports of them not working correctly.
2. There are only 2 others attributes that have `Computed` set, so I think it's reasonable for us to fix them now. If there are more (says 5 or 10, spanning multiple resources) then I'd agree we shouldn't fix.

File: pkg/artifactory/resource_artifactory_user.go (hunk 3 above)
Comment (chb0github) [reply pkg/artifactory/resource_artifactory_user.go:13]: Then it's being used somewhere - you'd get a compile error if you had an unused import. @maheshjfrog delete it and see what breaks. It might require you C&P code into here. 

There maybe some lingering references to the jfrog client that ultimately should be removed

File: pkg/artifactory/resource_artifactory_user.go [hunk 4]
```diff
@@ -68,14 +68,12 @@ func resourceArtifactoryUser() *schema.Resource {
 			"disable_ui_access": {
 				Type:     schema.TypeBool,
 				Optional: true,
-				Computed: true,
```
Comment (alexhung) [inline pkg/artifactory/resource_artifactory_user.go:60]: The Artifactory data schema has a default value, let's set them here (as well as for `internal_password_disabled` attribute.

File: pkg/artifactory/resource_artifactory_user.go [hunk 5]
```diff
@@ -57,14 +69,14 @@ func resourceArtifactoryUser() *schema.Resource {
...
 				Description: "When enabled, this user can only access the system through the REST API." +
 					" This option cannot be set if the user has Admin privileges.",
 			},
 			"internal_password_disabled": {
 				Type:     schema.TypeBool,
 				Optional: true,
-				Computed: true,
+				Default:  false,
 				Description: "When enabled, disables the fallback mechanism for using an internal password when " +
 					"external authentication (such as LDAP) is enabled.",
```
Comment (alexhung) [inline pkg/artifactory/resource_artifactory_user.go:81]: Please include the default value in the description, as well as in the doc Markdown file.

**Review by alexhung — DISMISSED** [review]
Other than the default values in description/doc, this is good to go.

File: docs/resources/artifactory_user.md [hunk 6]
```diff
@@ -25,9 +25,9 @@ The following arguments are supported:
 
 * `name` - (Required) Username for user.
 * `email` - (Required) Email for user.
-* `admin` - (Optional) When enabled, this user is an administrator with all the ensuing privileges.
-* `profile_updatable` - (Optional) When set, this user can update his profile details (except for the password. Only an administrator can update the password).
-* `disable_ui_access` - (Optional) When set, this user can only access Artifactory through the REST API. This option cannot be set if the user has Admin privileges.
+* `admin` - (Optional) When enabled, this user is an administrator with all the ensuing privileges. Default value is `false`.
+* `profile_updatable` - (Optional) When set, this user can update his profile details (except for the password. Only an administrator can update the password). Default value is `true`.
+* `disable_ui_access` - (Optional) When set, this user can only access Artifactory through the REST API. This option cannot be set if the user has Admin privileges. Default value is `true`.
```
Comment (chb0github) [inline docs/resources/artifactory_user.md:30]: What was the default before? I don't like making this assumption - so, whatever it is, let's not change it

File: pkg/artifactory/resource_artifactory_user.go [hunk 7]
```diff
@@ -42,13 +54,13 @@ func resourceArtifactoryUser() *schema.Resource {
...
 				Optional:    true,
-				Computed:    true,
+				Default:     false,
 				Description: "When enabled, this user is an administrator with all the ensuing privileges.",
 			},
 			"profile_updatable": {
 				Type:     schema.TypeBool,
 				Optional: true,
-				Computed: true,
+				Default:  true,
```
Comment (chb0github) [inline pkg/artifactory/resource_artifactory_user.go:63]: This is the default from RT?

File: pkg/artifactory/resource_artifactory_user.go [hunk 8]
```diff
@@ -166,7 +178,7 @@ func resourceUserCreate(d *schema.ResourceData, m interface{}) error {
 
 	d.SetId(user.Name)
 	return resource.Retry(d.Timeout(schema.TimeoutCreate), func() *resource.RetryError {
-		result := &services.User{}
+		result := &User{}
```
Comment (chb0github) [inline pkg/artifactory/resource_artifactory_user.go:181]: Nice catch. I would love to see how much more exposure we have to the jfrog client

**Review by chb0github — APPROVED** [review]
I just want to make sure we are maintaining existing defaults from RT, now that we've removed the `omitempty` - I think we have

File: pkg/artifactory/resource_artifactory_user.go (hunk 7 above)
Comment (maheshjfrog) [reply pkg/artifactory/resource_artifactory_user.go:63]: Yes. Checked based on https://www.jfrog.com/confluence/display/JFROG/Security+Configuration+JSON#SecurityConfigurationJSON-application/vnd.org.jfrog.artifactory.security.User+json

File: docs/resources/artifactory_user.md (hunk 6 above)
Comment (maheshjfrog) [reply docs/resources/artifactory_user.md:30]: There was no default before. It had Computed: true.
