### PR TITLE
Fix response status code checking

### LINKED ISSUE #221: Error after a remote repository was deleted
**Describe the bug**
I have created a remote repository with the following code :

```
resource "artifactory_remote_repository" "npmproxy" {
  key             = "npmproxy"
  package_type    = "npm"
  url             = "https://registry.npmjs.org/"
  repo_layout_ref = "npm-default"
  property_sets   = [
    "artifactory",
  ]

  unused_artifacts_cleanup_period_hours = 10100
  retrieval_cache_period_seconds = 600
  missed_cache_period_seconds = 1800
}
```

After a `terraform apply`, the repository is created.

Then I go in the WebUI and delete this repository.

It's now impossible to perform a `terraform plan` or `terraform apply`. I have got the followinf error :

```
$ terraform apply 
artifactory_general_security.security: Refreshing state... [id=security]
artifactory_oauth_settings.oauth: Refreshing state... [id=oauth_settings]
artifactory_remote_repository.npmproxy: Refreshing state... [id=npmproxy]
╷
│ Warning: Usage of Undocumented Artifactory API Endpoints
│ 
│   with artifactory_general_security.security,
│   on general-security.tf line 2, in resource "artifactory_general_security" "security":
│    2: resource "artifactory_general_security" "security" {
│ 
│ The artifactory_general_security resource uses endpoints that are undocumented and may not work with SaaS environments, or may change without notice.
│ 
│ (and one more similar warning elsewhere)
╵
╷
│ Error: 
│ 400 GET https://repos.tech.orange/artifactory/api/repositories/npmproxy
│ {
│   "errors" : [ {
│     "status" : 400,
│     "message" : "Bad Request"
│   } ]
│ }
│ 
│   with artifactory_remote_repository.npmproxy,
│   on remote-repo.tf line 1, in resource "artifactory_remote_repository" "npmproxy":
│    1: resource "artifactory_remote_repository" "npmproxy" {
│ 
╵

```

Artifactory version : 7.27.6
Terraform : 1.0.5
Artifactory provider : 2.6.19

**Requirements for and issue**
- [X] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue)
- [X] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [X] Your version of terraform

**Expected behavior**
When I perform a terraform plan after a remote repository was delete, I want to Terraform informs me the remote repository will be created.

### PR DESCRIPTION
**Pull request by alexhung**
Fix #221 

Artifactory API for `GET /api/repositories/{{repo_key}}` returns 400 status code for missing/not found repo. Update code to check for 400 as well as 404. This will ensure TF understands the repo is missing and requires to be re-created.

### CODE REVIEW

File: GNUmakefile [hunk 1]
```diff
@@ -37,11 +37,10 @@ attach:
 	dlv --listen=:2345 --headless=true --api-version=2 --accept-multiclient attach $$(pgrep terraform-provider-artifactory)
 
 acceptance: fmtcheck
-	export TF_ACC=1
-	test -n ARTIFACTORY_USERNAME && test -n ARTIFACTORY_PASSWORD && test -n ARTIFACTORY_URL \
+	export TF_ACC=true && \
```
Comment (chb0github) [inline GNUmakefile:40]: This doesn't seem to work at all. I think you can just delete it

File: pkg/artifactory/provider.go [hunk 2]
```diff
@@ -11,7 +11,7 @@ import (
 )
 
 // Version for some reason isn't getting updated by the linker
-var Version = "2.6.18"
+var Version = "2.6.20"
```
Comment (chb0github) [inline pkg/artifactory/provider.go:14]: Mmm, because of the changes to make, you can set this to anything you like and the linker should overwrite it. Meaning, no need to ever change it again

File: pkg/artifactory/repositories.go [hunk 3]
```diff
@@ -155,7 +155,7 @@ func mkRepoRead(pack PackFunc, construct Constructor) schema.ReadContextFunc {
 		resp, err := m.(*resty.Client).R().SetResult(repo).Get(repositoriesEndpoint + d.Id())
 
 		if err != nil {
-			if resp != nil && (resp.StatusCode() == http.StatusNotFound) {
+			if resp != nil && (resp.StatusCode() == http.StatusBadRequest || resp.StatusCode() == http.StatusNotFound) {
```
Comment (chb0github) [inline pkg/artifactory/repositories.go:158]: it might be a little cleaner to use a case statement?

**Review by chb0github — DISMISSED** [review]

File: GNUmakefile (hunk 1 above)
Comment (alexhung) [reply GNUmakefile:40]: Which part doesn't work?

File: pkg/artifactory/repositories.go (hunk 3 above)
Comment (alexhung) [reply pkg/artifactory/repositories.go:158]: How so?

File: GNUmakefile (hunk 1 above)
Comment (chb0github) [reply GNUmakefile:41]: the `export` part - You need to export before running the tests

**Review by chb0github — APPROVED** [review]
I just have some suggestions

File: GNUmakefile (hunk 1 above)
Comment (alexhung) [reply GNUmakefile:41]: The `&&` part does the trick. Works for me in my shell.

File: pkg/artifactory/repositories.go (hunk 3 above)
Comment (alexhung) [reply pkg/artifactory/repositories.go:158]: The `resp != nil` check makes it not as nice.
