### PR TITLE
GH-318 add project_key and project_environments support to repos

### LINKED ISSUE #318: Project level repo creation
The way we have set up Jfrog in our organization is that we request a new project and are given the project admin rights to that project. We can only create resources in that project, (By resources I mean creation of repositories) so I guess I'm just failing to understand how to create a repositories scoped at the project level. I'm using to pass in the key 'projectKey' which is listed in the REST API documentation. https://www.jfrog.com/confluence/display/JFROG/Repository+Configuration+JSON
something like this- 
`resource "artifactory_local_repository" "pypi-libs" {
  key             = "pypi-libs"
  **projectKey = 'XYZ**
  package_type    = "pypi"
  repo_layout_ref = "simple-default"
  description     = "A pypi repository for python packages"
}`

### PR DESCRIPTION
**Pull request by alexhung**
Fixes #318 and also https://github.com/jfrog/terraform-provider-project/issues/21

### CODE REVIEW

**Comment by maheshjfrog** [comment]
I think, User documentation (under docs folder) needs to be updated.

**Comment by alexhung** [comment]
@maheshjfrog I considered that but given how we include the JSON schema in the doc as reference, and we only include repo specific attribute documentation, I wasn't sure we need to add this to the doc.

I'm open to be convinced though.

**Comment by maheshjfrog** [comment]
> 

May be it depends on what our users expect to be communicated in the docs. 
My thoughts, we list all the supported attributes for the resources that are managed.
Fine with your choice.

File: pkg/artifactory/repositories.go [hunk 1]
```diff
@@ -18,6 +19,8 @@ const repositoriesEndpoint = "artifactory/api/repositories/"
 
 type LocalRepositoryBaseParams struct {
 	Key                    string   `hcl:"key" json:"key,omitempty"`
+	ProjectKey             string   `json:"projectKey"`
+	ProjectEnvironments    []string `hcl:"project_environments" json:"environments"`
```
Comment (chb0github) [inline pkg/artifactory/repositories.go:23]: It should auto generate the hcl for you

File: pkg/artifactory/repositories.go [hunk 2]
```diff
@@ -68,29 +71,31 @@ type ContentSynchronisationSource struct {
...
-	BlackedOut               *bool  `hcl:"blacked_out" json:"blackedOut,omitempty"`
-	XrayIndex                *bool  `hcl:"xray_index" json:"xrayIndex,omitempty"`
-	PropagateQueryParams     bool   `hcl:"propagate_query_params" json:"propagateQueryParams"`
-	PriorityResolution       bool   `hcl:"priority_resolution" json:"priorityResolution"`
-	StoreArtifactsLocally    *bool  `hcl:"store_artifacts_locally" json:"storeArtifactsLocally,omitempty"`
-	SocketTimeoutMillis      int    `hcl:"socket_timeout_millis" json:"socketTimeoutMillis,omitempty"`
-	LocalAddress             string `hcl:"local_address" json:"localAddress,omitempty"`
-	RetrievalCachePeriodSecs int    `hcl:"retrieval_cache_period_seconds" json:"retrievalCachePeriodSecs,omitempty"`
+	Key                      string   `hcl:"key" json:"key,omitempty"`
+	ProjectKey               string   `json:"projectKey"`
```
Comment (chb0github) [inline pkg/artifactory/repositories.go:75]: Here you don't define an hcl, but below you do - I just want to make sure you understand how this will work

File: pkg/artifactory/repositories.go (hunk 1 above)
Comment (alexhung) [reply pkg/artifactory/repositories.go:23]: Yes, I forgot!

File: pkg/artifactory/repositories.go (hunk 2 above)
Comment (alexhung) [reply pkg/artifactory/repositories.go:75]: I keep thinking it derives the hcl attribute from the json, but it doesn't obviously. Doh!

File: pkg/artifactory/resource_artifactory_federated_repository_test.go [hunk 3]
```diff
@@ -129,3 +132,109 @@ func TestAccFederatedRepoAllTypes(t *testing.T) {
...
+	})
+}
+
+func TestAccFederatedRepositoryWithInvalidProjectKeyGH318(t *testing.T) {
+	if skip, reason := skipFederatedRepo(); skip {
+		t.Skipf(reason)
+	}
+
+	rand.Seed(time.Now().UnixNano())
+	projectKey := fmt.Sprintf("t%d", rand.Intn(100000000))
```
Comment (chb0github) [inline pkg/artifactory/resource_artifactory_federated_repository_test.go:200]: `randInt()` already does this exact thing

File: pkg/artifactory/resource_artifactory_local_repository_test.go [hunk 4]
```diff
@@ -464,6 +467,129 @@ func TestAccLocalGenericRepository(t *testing.T) {
 	})
 }
 
+func TestAccLocalGenericRepositoryWithProjectAttributesGH318(t *testing.T) {
+
+	rand.Seed(time.Now().UnixNano())
+	projectKey := fmt.Sprintf("t%d", rand.Intn(100000000))
```
Comment (chb0github) [inline pkg/artifactory/resource_artifactory_local_repository_test.go:473]: `randInt()` in utils file

File: pkg/artifactory/util.go [hunk 5]
```diff
@@ -123,6 +123,14 @@ func randBool() bool {
 	return randomInt()%2 == 0
 }
 
+func randProjectEnv() string {
```
Comment (chb0github) [inline pkg/artifactory/util.go:126]: instead of this, use `randSelect("DEV","PROD")`

**Review by chb0github — CHANGES_REQUESTED** [review]
A few comments but nothing serious. Good work

File: pkg/artifactory/resource_artifactory_federated_repository_test.go (hunk 3 above)
Comment (alexhung) [reply pkg/artifactory/resource_artifactory_federated_repository_test.go:200]: No, it doesn't. Here I need to restrict the number to 9 digits only. `randInt()` can get above that.

File: pkg/artifactory/repositories.go [hunk 6]
```diff
@@ -322,13 +329,30 @@ var repoTypesLikeGeneric = []string{
...
+		Description:      "Project key for assigning this repository to. When assigning repository to a project, repository key must be prefixed with project key, separated by a dash.",
+	},
+	"project_environments": {
+		Type:        schema.TypeSet,
+		Elem:        &schema.Schema{Type: schema.TypeString},
+		MinItems:    1,
+		MaxItems:    2,
+		Set:         schema.HashString,
+		Optional:    true,
+		Description: `Project environment for assigning this repository to. Allow values: "DEV" or "PROD"`,
```
Comment (chb0github) [inline pkg/artifactory/repositories.go:354]: Is this is the case, then you want to validate that, right? But my understanding is that project environments are entirely arbitrary

File: pkg/artifactory/repositories.go [hunk 7]
```diff
@@ -391,13 +414,28 @@ var baseLocalRepoSchema = map[string]*schema.Schema{
...
+		ValidateDiagFunc: projectKeyValidator,
+		Description:      "Project key for assigning this repository to. Must be 3 - 10 lowercase alphanumeric characters. When assigning repository to a project, repository key must be prefixed with project key, separated by a dash.",
+	},
+	"project_environments": {
+		Type:        schema.TypeSet,
+		Elem:        &schema.Schema{Type: schema.TypeString},
+		MaxItems:    2,
+		Set:         schema.HashString,
+		Optional:    true,
+		Description: `Project environment for assigning this repository to. Allow values: "DEV" or "PROD"`,
```
Comment (chb0github) [inline pkg/artifactory/repositories.go:437]: Validation?

File: pkg/artifactory/repositories.go [hunk 8]
```diff
@@ -1061,6 +1132,9 @@ func mkResourceSchema(skeema map[string]*schema.Schema, packer PackFunc, unpack
 		},
 
 		Schema: skeema,
+		CustomizeDiff: customdiff.All(
+			projectEnvironmentsDiff,
```
Comment (chb0github) [inline pkg/artifactory/repositories.go:1136]: Why do you have `customdiff.all` when you only have 1?

File: pkg/artifactory/resource_artifactory_federated_repository_test.go [hunk 9]
```diff
@@ -129,3 +132,101 @@ func TestAccFederatedRepoAllTypes(t *testing.T) {
 		})
 	}
 }
+
+func TestAccFederatedRepoWithProjectAttributesGH318(t *testing.T) {
+	rand.Seed(time.Now().UnixNano())
+	projectKey := fmt.Sprintf("t%d", rand.Intn(100000000))
```
Comment (chb0github) [inline pkg/artifactory/resource_artifactory_federated_repository_test.go:138]: There is a function called `randInt()` and works just like this

**Review by chb0github — APPROVED** [review]

**Review by chb0github — CHANGES_REQUESTED** [review]
Doc updates? `sample.tf`?

**Review by chb0github — APPROVED** [review]
