### PR TITLE
GH-610 Fix import issues for "configuration" resources

### LINKED ISSUE #610: repository_layout's import doesn't import state properly
After importing an existing repository layout, when running `terraform plan` I get the following output:
```
  # artifactory_repository_layout.this["maven-2-default"] must be replaced
-/+ resource "artifactory_repository_layout" "this" {
      + artifact_path_pattern               = "[orgPath]/[module]/[baseRev](-[folderItegRev])/[module]-[baseRev](-[fileItegRev])(-[classifier]).[ext]"
      + descriptor_path_pattern             = "[orgPath]/[module]/[baseRev](-[folderItegRev])/[module]-[baseRev](-[fileItegRev])(-[classifier]).[ext]"
      + distinctive_descriptor_path_pattern = true
      + file_integration_revision_regexp    = ".*"
      + folder_integration_revision_regexp  = ".*"
      ~ id                                  = "maven-2-default" -> (known after apply)
      + name                                = "maven-2-default" # forces replacement
    }
```

I'd expect 
the name field to be "unchanged", not causing a replacement. If the current config matches the artifactory state, no planned changes should be shown. 
All the other attributes should show either "changed/unchanged" instead of "add", although this is likely caused by the "replacement".
The current behavior makes it a rather scary import action, since terraform plan will show replacements for all repository layouts, even if the terraform defintion matches the state of the artifactory.

I'd appreciate if that could be fixed in the near future.

```
Terraform v1.3.6
+ provider registry.terraform.io/jfrog/artifactory v6.21.8
jf rt curl api/system/version
{
  "version" : "7.33.12",
```

### PR DESCRIPTION
**Pull request by alexhung**
Fixes #610 

## Details

The importer has not been setup to copy the resource's ID to the data struct's identifying attribute. For example, for repository the attribute 'key' is used in read function to fetch repo's data. For others, it may be the 'name' field, depending on the resource/API.

We can't just change the read function to use `d.Id()` because during import, there's no Terraform state yet so `d.Id()` returns nothing.

For example:

```hcl
resource "artifactory_proxy" "some-proxy-id" {
  key               = "proxy-1"
  host              = "https://fake-proxy.org"
  port              = 8080
  username          = "fake-user"
  password          = "fake-password"
  nt_host           = "fake-nt-host"
  nt_domain         = "fake-nt-domain"
  platform_default  = false
  redirect_to_hosts = ["foo"]
  services          = ["jfrt"]
}
```

In this case, the resource ID is `some-proxy-id` and the actual proxy key is `proxy-1`. Therefore, the importer function needs to copy the resource ID into the identifying attribute so the read function can use that attribute with the API.

E.g. for importing:

```sh
$ terraform import artifactory_proxy.some-proxy-id proxy-1
```

## Changes

- Fix packing function for `artifactory_repository_layout` 

For `artifactory_backup`, `artifactory_ldap_setting`, `artifactory_ldap_group_setting`, `artifactory_repository_layout`, `artifactory_proxy`, `artifactory_property_set`:
- Fix importer func to ensure data source ID is copied to the correct attribute (for use by read func later)
- Use struct identifying field (e.g. `key`, `name`, etc.) in read func.
- Ensure we return error to Terraform if we can't find matching resource in read func.
- Add import and update tests

### CODE REVIEW

File: pkg/artifactory/resource/repository/local/resource_artifactory_local_debian_repository.go [hunk 1]
```diff
@@ -33,7 +33,7 @@ var DebianLocalSchema = util.MergeMaps(
 
 type DebianLocalRepositoryParams struct {
 	RepositoryBaseParams
-	TrivialLayout           bool     `hcl:"trivial_layout" json:"debianTrivialLayout,omitempty"`
+	TrivialLayout           bool     `hcl:"trivial_layout" json:"debianTrivialLayout"`
```
Comment (danielmkn) [inline pkg/artifactory/resource/repository/local/resource_artifactory_local_debian_repository.go:36]: DOes this attribute have a default value? Otherwise, we can get a null pointer, right?

Comment (alexhung) [reply pkg/artifactory/resource/repository/local/resource_artifactory_local_debian_repository.go:36]: Good catch. Let me check.

File: pkg/artifactory/resource/configuration/resource_artifactory_backup.go [hunk 2]
```diff
@@ -120,17 +120,18 @@ func ResourceArtifactoryBackup() *schema.Resource {
 	}
 
 	var resourceBackupRead = func(_ context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
-		backups := &Backups{}
-		backup := unpackBackup(d)
+		data := &util.ResourceData{ResourceData: d}
+		key := data.GetString("key", false)
 
+		backups := &Backups{}
```
Comment (Turhsus) [inline pkg/artifactory/resource/configuration/resource_artifactory_backup.go:126]: On my PR for the user datasource we saw that we should not make this a reference, but the object itself. Is the reasoning different here, or should this also be an object?

File: pkg/artifactory/resource/configuration/resource_artifactory_ldap_group_setting.go [hunk 3]
```diff
@@ -103,24 +107,23 @@ Hierarchy: The user's DN is indicative of the groups the user belongs to by usin
 	}
 
 	var resourceLdapGroupSettingsRead = func(_ context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
-		ldapGroupConfigs := &XmlLdapGroupConfig{}
-		ldapGroupSetting := unpackLdapGroupSetting(d)
+		data := &util.ResourceData{ResourceData: d}
+		name := data.GetString("name", false)
 
+		ldapGroupConfigs := &XmlLdapGroupConfig{}
```
Comment (Turhsus) [inline pkg/artifactory/resource/configuration/resource_artifactory_ldap_group_setting.go:113]: Same thing here, why do we choose to create the address of an object this time?

**Review by Turhsus — APPROVED** [review]
LGTM, submitted nonblocking questions

File: pkg/artifactory/resource/configuration/resource_artifactory_backup.go (hunk 2 above)
Comment (alexhung) [reply pkg/artifactory/resource/configuration/resource_artifactory_backup.go:126]: No different. This is also wrong. This is why we strive to not commit bad code because others will copy/paste them.

Comment (alexhung) [reply pkg/artifactory/resource/configuration/resource_artifactory_backup.go:126]: I will fix them 😄

**Review by danielmkn — APPROVED** [review]
