### PR TITLE
GH-744 upgrade issues

### LINKED ISSUE #744: Upgrading to 8.0.0 without any other changes updates or forces replacement of several resources
**Describe the bug**
Basically the title. No other changes were made except upgrading provider version (from 7.2.1). 
The complete list of changes are too large to be pasted here, so will instead provide examples.
Examples (names have been changed or redacted):

```terraform
  # module.security.artifactory_group.admins will be updated in-place
  ~ resource "artifactory_group" "admins" {
      + detach_all_users = false
      ~ id               = "Admins" -> (known after apply)
        name             = "Admins"
      ~ realm            = "scim" -> "internal"
      - users_names      = [] -> null
        # (7 unchanged attributes hidden)
    }
  
  # module.security.artifactory_scoped_token.example_token must be replaced
-/+ resource "artifactory_scoped_token" "example_token" {
      ~ access_token            = (sensitive value)
      ~ expires_in              = 31536000 # forces replacement -> (known after apply)
      ~ expiry                  = 1715328105 -> (known after apply)
      + grant_type              = "client_credentials" # forces replacement
      ~ id                      = "redacted -> (known after apply)
      + include_reference_token = false # forces replacement
      ~ issued_at               = 1683792105 -> (known after apply)
      ~ issuer                  = "jfac@xxx" -> (known after apply)
      + reference_token         = (sensitive value)
      + refresh_token           = (sensitive value)
      ~ scopes                  = [ # forces replacement
          - "applied-permissions/user",
        ] -> (known after apply)
      ~ subject                 = "jfac@xxx/users/example-user" -> (known after apply)
      ~ token_type              = "Bearer" -> (known after apply)
        # (2 unchanged attributes hidden)
    }
```
Also got several errors. Examples:

```
│ Error: Failed to decode resource from state
│ 
│ Error decoding
│ "module.security.artifactory_permission_target.example_target" from
│ previous state: missing expected {
╵
╷
│ Error: Unable to Read Previously Saved State for UpgradeResourceState
│ 
│   with module.security.artifactory_permission_target.other_target,
│   on ../modules/security/main.tf line 71, in resource "artifactory_permission_target" "other_target":
│   71: resource "artifactory_permission_target" "other_target" {
│ 
│ There was an error reading the saved resource state using the current
│ resource schema.
│ 
│ If this resource state was last refreshed with Terraform CLI 0.11 and
│ earlier, it must be refreshed or applied with an older provider version
│ first. If you manually modified the resource state, you will need to
│ manually modify it to match the current resource schema. Otherwise, please
│ report this to the provider developer:
│ 
│ AttributeName("build"): invalid JSON, expected "{", got "["
```
Terraform 1.4.2
Artifactory 8.0.0

**Expected behavior**
No changes to resources.

### PR DESCRIPTION
**Pull request by alexhung**
Fix #744 

* Fixed unintended state drift when upgrading from pre-migrated provider for:
  * resource/artifactory_group
  * resource/artifactory_scoped_token
  * resource/artifactory_managed_user
  * resource/artifactory_user
  * resource_permission_target
* Add migration acceptance tests to ensure plan is 'clean' after upgrading from previous version of the provider

### CODE REVIEW

**Review by MahithaB — APPROVED** [review]

**Review by shrajfr12 — DISMISSED** [review]

File: pkg/artifactory/resource/security/resource_artifactory_scoped_token.go [hunk 1]
```diff
@@ -305,7 +341,7 @@ func (r *ScopedTokenResource) Create(ctx context.Context, req resource.CreateReq
 
 	// Convert from Terraform data model into API data model
 	accessTokenPostBody := AccessTokenPostRequestAPIModel{
-		GrantType:             data.GrantType.ValueString(),
+		GrantType:             "client_credentials",
```
Comment (danielmkn) [inline pkg/artifactory/resource/security/resource_artifactory_scoped_token.go:344]: This attribute has a default value of "client_credentials", no need to hardcode it here.

**Review by danielmkn — CHANGES_REQUESTED** [review]
