### PR TITLE
Repository Layout defaulted to as per Package Type & Repository Type provided repo_layout_ref is not set in the Resource

### LINKED ISSUE #282: Default repo_layout_ref for artifactory_local_docker_v2_repository resources is maven-2-default
**Describe the bug**
When creating a resource of type artifactory_local_docker_v2_repository, unless overriden you'll end up with a repo with layout maven-2-default. This doesn't seem to cause any issues as such, just in the screenshot in https://www.jfrog.com/confluence/display/JFROG/Docker+Registry it seems to imply that simple-default would be the type to choose.

**Requirements for and issue**
- [ ] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue)
- [ ] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [ ] Your version of terraform

Terraform Version

```
Terraform v1.1.1
on darwin_amd64
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/jfrog/artifactory v2.9.1
```

Artifactory version

```
{
  "version" : "7.31.10",
  "revision" : "73110900",
  "addons" : [ "ha", "build", "docker", "vagrant", "replication", "filestore", "plugins", "gems", "composer", "npm", "bower", "git-lfs", "nuget", "debian", "opkg", "rpm", "cocoapods", "conan", "vcs", "pypi", "release-bundle", "jf-event", "replicator", "keys", "alpine", "cargo", "chef", "cran", "federated", "git", "go", "helm", "observability", "pub", "rest", "swift", "conda", "terraform", "tracker", "license", "puppet", "ldap", "sso", "layouts", "properties", "search", "securityresourceaddon", "filtered-resources", "p2", "watch", "webstart", "support", "xray", "retention" ],
  "license" : "XXX"
}
```

**Expected behavior**
Based on the screenshot in the JFrog documentation I'd expect the default layout to be simple-default for local Docker repositories.

**Additional context**
-

### PR DESCRIPTION
**Pull request by dasmanas**
closes #282 
Repository Layout defaulted to as per Package Type & Repository Type provided repo_layout_ref is not set in the Resource

### CODE REVIEW

File: pkg/artifactory/resource_artifactory_local_alpine_repository.go [hunk 1]
```diff
@@ -4,37 +4,39 @@ import (
...
+
+	type AlpineLocalRepo struct {
+		LocalRepositoryBaseParams
+		PrimaryKeyPairRef string `hcl:"primary_keypair_ref" json:"primaryKeyPairRef"`
+	}
+
+	var unPackLocalAlpineRepository = func(data *schema.ResourceData) (interface{}, string, error) {
+		d := &ResourceData{ResourceData: data}
+		repo := AlpineLocalRepo{
+			LocalRepositoryBaseParams: unpackBaseRepo("local", data, "alpine"),
```
Comment (alexhung) [inline pkg/artifactory/resource_artifactory_local_alpine_repository.go:27]: Please use `pkt` here

File: pkg/artifactory/resource_artifactory_local_generic_repository.go [hunk 2]
```diff
@@ -15,5 +15,6 @@ func resourceArtifactoryLocalGenericRepository(pkt string) *schema.Resource {
 		repo := unpackBaseRepo("local", data, pkt)
 		return repo, repo.Id(), nil
 	}
-	return mkResourceSchema(baseLocalRepoSchema, inSchema(baseRemoteSchema), unpack, constructor)
+	baseLocalRepoSchema := getBaseLocalRepoSchema(pkt)
+	return mkResourceSchema(baseLocalRepoSchema, inSchema(baseLocalRepoSchema), unpack, constructor)
```
Comment (alexhung) [inline pkg/artifactory/resource_artifactory_local_generic_repository.go:19]: 👍🏼

File: pkg/artifactory/resource_artifactory_local_alpine_repository.go [hunk 3]
```diff
@@ -4,37 +4,39 @@ import (
...
-	"primary_keypair_ref": {
-		Type:     schema.TypeString,
-		Optional: true,
-		Description: "Used to sign index files in Alpine Linux repositories. " +
-			"See: https://www.jfrog.com/confluence/display/JFROG/Alpine+Linux+Repositories#AlpineLinuxRepositories-SigningAlpineLinuxIndex",
-	},
-}, compressionFormats)
-
 func resourceArtifactoryLocalAlpineRepository() *schema.Resource {
+	const pkt = "alpine"
```
Comment (chb0github) [inline pkg/artifactory/resource_artifactory_local_alpine_repository.go:8]: You do this repeatedly where you declare a constant, and then use it once. All that does is add an extra line of code. 

In this cause you could use it twice, but you're not. Get rid of this constant - all of them - they don't add any value

File: pkg/artifactory/resource_artifactory_local_repository_test.go [hunk 4]
```diff
@@ -661,3 +662,47 @@ func TestAccLocalAllRepoTypes(t *testing.T) {
 		})
 	}
 }
+
+func makeLocalRepoTestCase(repoType string, t *testing.T) (*testing.T, resource.TestCase) {
+	name := fmt.Sprintf("terraform-local-%s-%d-full", repoType, rand.Int())
+	resourceName := fmt.Sprintf("artifactory_local_%s_repository.%s", repoType, name)
+	repoLayoutRef := getDefaultLocalRepoLayoutRef(repoType, true)
```
Comment (alexhung) [inline pkg/artifactory/resource_artifactory_local_repository_test.go:669]: As mentioned before, please use separate test utility func instead of combining with production code

File: pkg/artifactory/resource_artifactory_local_alpine_repository.go [hunk 5]
```diff
@@ -4,37 +4,39 @@ import (
...
+			Type:     schema.TypeString,
+			Optional: true,
+			Description: "Used to sign index files in Alpine Linux repositories. " +
+				"See: https://www.jfrog.com/confluence/display/JFROG/Alpine+Linux+Repositories#AlpineLinuxRepositories-SigningAlpineLinuxIndex",
+		},
+	}, compressionFormats)
+
+	type AlpineLocalRepo struct {
+		LocalRepositoryBaseParams
+		PrimaryKeyPairRef string `hcl:"primary_keypair_ref" json:"primaryKeyPairRef"`
```
Comment (chb0github) [inline pkg/artifactory/resource_artifactory_local_alpine_repository.go:21]: The default packer will actually do the `hcl` properly for you. You only need be explicit for overrides

File: pkg/artifactory/resource_artifactory_local_alpine_repository.go (hunk 1 above)
Comment (chb0github) [inline pkg/artifactory/resource_artifactory_local_alpine_repository.go:27]: Notice you have `alpine` here too?

File: pkg/artifactory/resource_artifactory_remote_helm_repository.go [hunk 6]
```diff
@@ -5,61 +5,63 @@ import (
...
+		ExternalDependenciesEnabled  bool     `hcl:"external_dependencies_enabled" json:"externalDependenciesEnabled"`
+		ExternalDependenciesPatterns []string `hcl:"external_dependencies_patterns" json:"externalDependenciesPatterns"`
+	}
 
-func resourceArtifactoryRemoteHelmRepository() *schema.Resource {
-	return mkResourceSchema(helmRemoteSchema, defaultPacker, unpackhelmRemoteRepo, func() interface{} {
+	var unpackHelmRemoteRepo = func(s *schema.ResourceData) (interface{}, string, error) {
+		d := &ResourceData{s}
+		repo := HelmRemoteRepo{
+			RemoteRepositoryBaseParams:   unpackBaseRemoteRepo(s, "helm"),
```
Comment (alexhung) [inline pkg/artifactory/resource_artifactory_remote_helm_repository.go:51]: Use `packageType`

File: pkg/artifactory/resource_artifactory_remote_repository_test.go [hunk 7]
```diff
@@ -67,8 +67,54 @@ func TestKeyHasSpecialCharsFails(t *testing.T) {
 	})
 }
 
+/*type TestCheckFunction func(string ...) resource.TestCheckFunc
```
Comment (alexhung) [inline pkg/artifactory/resource_artifactory_remote_repository_test.go:70]: Please clean up commented out code

File: pkg/artifactory/resource_artifactory_remote_repository_test.go [hunk 8]
```diff
@@ -86,7 +132,27 @@ func TestAccRemoteDockerRepository(t *testing.T) {
 }
 
 func TestAccRemoteCargoRepository(t *testing.T) {
-	_, testCase := mkNewRemoteTestCase("cargo", t, map[string]interface{}{
+	const packageType = "cargo"
+	//resource.TestCheckResourceAttr(resourceName, "repo_layout_ref", getDefaultRemoteRepoLayoutRef(packageType), //Check to ensure repository layout is set as per default even when it is not passed.
```
Comment (alexhung) [inline pkg/artifactory/resource_artifactory_remote_repository_test.go:136]: Please clean up

File: pkg/artifactory/resource_artifactory_local_debian_repository.go [hunk 9]
```diff
@@ -4,53 +4,54 @@ import (
...
+		TrivialLayout           bool     `hcl:"trivial_layout" json:"debianTrivialLayout,omitempty"`
+		IndexCompressionFormats []string `hcl:"index_compression_formats" json:"optionalIndexCompressionFormats,omitempty"`
+		PrimaryKeyPairRef       string   `hcl:"primary_keypair_ref" json:"primaryKeyPairRef,omitempty"`
+		SecondaryKeyPairRef     string   `hcl:"secondary_keypair_ref" json:"secondaryKeyPairRef,omitempty"`
+	}
+
+	var unPackLocalDebianRepository = func(data *schema.ResourceData) (interface{}, string, error) {
+		d := &ResourceData{ResourceData: data}
+		repo := DebianLocalRepositoryParams{
+			LocalRepositoryBaseParams: unpackBaseRepo("local", data, "debian"),
```
Comment (chb0github) [inline pkg/artifactory/resource_artifactory_local_debian_repository.go:40]: You can use your constant here

File: pkg/artifactory/resource_artifactory_local_docker_repository.go [hunk 10]
```diff
@@ -76,10 +73,42 @@ func resourceArtifactoryLocalDockerV2Repository() *schema.Resource {
...
+	})
+
 	// this is necessary because of the pointers
 	skeema := mergeSchema(map[string]*schema.Schema{}, dockerV1LocalSchema)
-	for key, value := range dockerV2LocalSchema {
-		skeema[key].Description = value.Description
+
+	var unPackLocalDockerV1Repository = func(data *schema.ResourceData) (interface{}, string, error) {
+		repo := DockerLocalRepositoryParams{
+			LocalRepositoryBaseParams: unpackBaseRepo("local", data, "docker"),
```
Comment (chb0github) [inline pkg/artifactory/resource_artifactory_local_docker_repository.go:104]: use your constant here

File: pkg/artifactory/resource_artifactory_remote_repository_test.go [hunk 11]
```diff
@@ -67,8 +67,54 @@ func TestKeyHasSpecialCharsFails(t *testing.T) {
...
+			"enabled":                         false, // even when set to true, it seems to come back as false on the wire
+			"statistics_enabled":              true,
+			"properties_enabled":              true,
+			"source_origin_absence_detection": true,
+		},
+	})
+	resource.Test(t, testCase)
+}
+
+func TestAccRemoteDockerRepositoryWithAdditionalCheckFunctions(t *testing.T) {
```
Comment (alexhung) [inline pkg/artifactory/resource_artifactory_remote_repository_test.go:115]: How is this test case different from `TestAccRemoteDockerRepository`? Same for the rest in this file.

File: pkg/artifactory/resource_artifactory_local_repository_test.go (hunk 4 above)
Comment (chb0github) [inline pkg/artifactory/resource_artifactory_local_repository_test.go:669]: So this function:
`getDefaultLocalRepoLayoutRef` I didn't see it implemented in this PR - when was this created?

File: pkg/artifactory/resource_artifactory_remote_repository_test.go [hunk 12]
```diff
@@ -376,6 +494,77 @@ func mkNewRemoteTestCase(repoType string, t *testing.T, extraFields map[string]i
...
+	const remoteRepoFull = `
+		resource "artifactory_remote_%s_repository" "%s" {
+%s
+		}
+	`
+	extraChecks := mapToTestChecks(fqrn, extraFields)
+	defaultChecks := mapToTestChecks(fqrn, allFields)
+
+	var addCheckFunctions = []resource.TestCheckFunc{
+		resource.TestCheckResourceAttr(fqrn, "repo_layout_ref", getDefaultRemoteRepoLayoutRef(repoType)), //Check to ensure repository layout is set as per default even when it is not passed.
```
Comment (alexhung) [inline pkg/artifactory/resource_artifactory_remote_repository_test.go:549]: This test case is unnecessarily large. To test `repo_layout_ref`, we only need to have a minimum test case. This added some much complexity that is unrelated to testing this attribute. Please make this a simple, straightforward test case.

File: pkg/artifactory/resource_artifactory_virtual_maven_repository.go [hunk 13]
```diff
@@ -43,29 +17,58 @@ type MavenVirtualRepositoryParams struct {
...
+			Optional:    true,
+			Description: "The keypair used to sign artifacts",
+		},
+	})
+
+	var unpackMavenVirtualRepository = func(s *schema.ResourceData) (interface{}, string, error) {
+		d := &ResourceData{s}
+
+		repo := MavenVirtualRepositoryParams{
+			VirtualRepositoryBaseParams: unpackBaseVirtRepo(s, "maven"),
```
Comment (alexhung) [inline pkg/artifactory/resource_artifactory_virtual_maven_repository.go:53]: Use `packageType`

**Review by alexhung — CHANGES_REQUESTED** [review]
Please include a summary of the change in the PR description.

Commit message should also be descriptive of the change.

See comments on the changes needed

File: pkg/artifactory/repositories.go [hunk 14]
```diff
@@ -330,426 +332,533 @@ var repoTypesLikeGeneric = []string{
...
+			MaxItems: 1,
+			Elem: &schema.Resource{
+				Schema: map[string]*schema.Schema{
+					"enabled": {
+						Type:        schema.TypeBool,
+						Optional:    true,
+						Default:     false,
+						Description: `(Optional) If set, Remote repository proxies a local or remote repository from another instance of Artifactory. Default value is 'false'.`,
+					},
+					"statistics_enabled": {
```
Comment (chb0github) [inline pkg/artifactory/repositories.go:655]: It's cool that you added these, but they weren't being used.

File: pkg/artifactory/repositories.go [hunk 15]
```diff
@@ -330,426 +332,533 @@ var repoTypesLikeGeneric = []string{
...
+			Type:     schema.TypeString,
+			Optional: true,
+			Description: "List of artifact patterns to exclude when evaluating artifact requests, in the form of x/y/**/z/*." +
+				"By default no artifacts are excluded.",
+		},
+		"repo_layout_ref": {
+			Type:     schema.TypeString,
+			Optional: true,
+			DefaultFunc: func() (interface{}, error) {
+				return getDefaultVirtualRepoLayoutRef(packageType), nil
```
[the remark this answers is not in the document]
Comment (chb0github) [reply pkg/artifactory/repositories.go:741]: YES!!!

File: pkg/artifactory/repositories.go [hunk 16]
```diff
@@ -330,426 +332,533 @@ var repoTypesLikeGeneric = []string{
...
+		},
+		"excludes_pattern": {
+			Type:     schema.TypeString,
+			Optional: true,
+			Computed: true,
+		},
+		"repo_layout_ref": {
+			Type:     schema.TypeString,
+			Optional: true,
+			DefaultFunc: func() (interface{}, error) {
```
Comment (chb0github) [inline pkg/artifactory/repositories.go:825]: So, in your 
```go
 getDefaultFederatedRepoLayoutRef(packageType)
```

If you change it to:
you can return a function and get rid of this ugliness:
```go

var repoRefDefault = func() func() (interface{}, error) {
	return func() (interface{}, error) { 
                getDefaultFederatedRepoLayoutRef(packageType), nil
          }
}()
```
 then you can just do `DefaultFunc: repoRefDefault` -

File: pkg/artifactory/repositories.go [hunk 17]
```diff
@@ -1132,11 +1241,231 @@ func mkResourceSchema(skeema map[string]*schema.Schema, packer PackFunc, unpack
...
+		Schema:        skeema,
 		CustomizeDiff: projectEnvironmentsDiff,
 	}
 }
 
+//Returns random string from a map[string]string
+func selectRandomFromMapOfStrings(m map[string]string) string {
+	mapLength := len(m)
+	allValues := make([]string, 0, mapLength)
+	for _, value := range m {
```
Comment (chb0github) [inline pkg/artifactory/repositories.go:1253]: How about you just loop through the map and randomly decide to select or not? Way simpler and no copying

```go
for _, value range m {
    if selectRand(true,false).(bool) {
     return value;
    }
}
```

File: pkg/artifactory/repositories.go [hunk 18]
```diff
@@ -1132,11 +1241,231 @@ func mkResourceSchema(skeema map[string]*schema.Schema, packer PackFunc, unpack
...
+		allValues = append(allValues, value)
+	}
+	s1 := rand.NewSource(time.Now().UnixNano())
+	r1 := rand.New(s1)
+	return allValues[r1.Intn(mapLength)]
+}
+
+func isSelectRandom(opts ...bool) bool {
```
[the remark this answers is not in the document]
Comment (chb0github) [reply pkg/artifactory/repositories.go:1261]: I literally don't know what this does. If you're trying to select random, there is already an implementation in this repo (see above). And, a random bool is trivial

```go
return r1.Int() % 2 == 0
```

File: pkg/artifactory/repositories.go [hunk 19]
```diff
@@ -1132,11 +1241,231 @@ func mkResourceSchema(skeema map[string]*schema.Schema, packer PackFunc, unpack
...
+			selectRandomFlag = val
+		default:
+			fmt.Printf("Option index is not defined. Index: %v, value: %v\n", i, val)
+		}
+	}
+	return selectRandomFlag
+}
+
+//Return the default repo layout of Local Repository type
+func getDefaultLocalRepoLayoutRef(repoType string, opts ...bool) string {
```
[the remark this answers is not in the document]
Comment (chb0github) [reply pkg/artifactory/repositories.go:1275]: Too much C&P

File: pkg/artifactory/repositories.go [hunk 20]
```diff
@@ -1132,11 +1241,231 @@ func mkResourceSchema(skeema map[string]*schema.Schema, packer PackFunc, unpack
...
+		"pub":       "simple-default",
+		"puppet":    "puppet-default",
+		"pypi":      "simple-default",
+		"sbt":       "sbt-default",
+		"vagrant":   "simple-default",
+		"rpm":       "simple-default",
+	}
+
+	if selectRandom {
+		repoLayout = selectRandomFromMapOfStrings(localDefaultRepoLayoutMap)
```
Comment (chb0github) [inline pkg/artifactory/repositories.go:1313]: In production code you almost never want random - but even here, this code could be better

```go
if selectRandom {
   return select...
}
```

Your else is entirely unnecessary

File: pkg/artifactory/repositories.go [hunk 21]
```diff
@@ -1132,11 +1241,231 @@ func mkResourceSchema(skeema map[string]*schema.Schema, packer PackFunc, unpack
...
+	} else {
+		if value, ok := localDefaultRepoLayoutMap[repoType]; ok {
+			repoLayout = value
```
Comment (chb0github) [inline pkg/artifactory/repositories.go:1316]: you could literally just return `value` here.

File: pkg/artifactory/repositories.go [hunk 22]
```diff
@@ -1132,11 +1241,231 @@ func mkResourceSchema(skeema map[string]*schema.Schema, packer PackFunc, unpack
...
+		}
+	}
+	return repoLayout
+}
+
+//Return the default repo layout of Remote Repository type
+func getDefaultRemoteRepoLayoutRef(repoType string, opts ...bool) string {
```
Comment (chb0github) [inline pkg/artifactory/repositories.go:1323]: Please don't do this. In fact, this whole function is unnecessary - all you need is this map - you don't need any function. 

And, I wouldn't even have a default - if your lookup fails, then panic because it's a type we don't support

File: pkg/artifactory/repositories.go [hunk 23]
```diff
@@ -1132,11 +1241,231 @@ func mkResourceSchema(skeema map[string]*schema.Schema, packer PackFunc, unpack
...
+	} else {
+		if value, ok := remoteDefaultRepoLayoutMap[repoType]; ok {
+			repoLayout = value
+		}
+	}
+	return repoLayout
+}
+
+//Return the default repo layout of Virtual Repository type
+func getDefaultVirtualRepoLayoutRef(repoType string, opts ...bool) string {
```
Comment (chb0github) [inline pkg/artifactory/repositories.go:1373]: Random in production code?

File: pkg/artifactory/repositories.go [hunk 24]
```diff
@@ -1132,11 +1241,231 @@ func mkResourceSchema(skeema map[string]*schema.Schema, packer PackFunc, unpack
...
+}
+
+//Return the default repo layout of Federated Repository type
+func getDefaultFederatedRepoLayoutRef(repoType string, opts ...bool) string {
+
+	selectRandom := isSelectRandom(opts...)
+	const defaultRepoLayout = "simple-default"
+	repoLayout := defaultRepoLayout
+
+	federatedDefaultRepoLayoutMap := map[string]string{
```
Comment (chb0github) [inline pkg/artifactory/repositories.go:1428]: Are these maps even different? I don't see how. And, I don't see why they should be

**Review by chb0github — CHANGES_REQUESTED** [review]
There is a bunch of work to do
Too much C&P
Conflating test/production code

File: pkg/artifactory/repositories.go (hunk 24 above)
Comment (dasmanas) [reply pkg/artifactory/repositories.go:1428]: The map is different
```
+------------------------------------------+-------------------------------------------+--------------------------------------------+----------------------------------------------+
|             Local Repository             |             Remote Repository             |             Virtual Repository             |             Federated Repository             |
+-----------------------+------------------+------------------------+------------------+-------------------------+------------------+---------------------------+------------------+
| Local Repository Type | repo_layout_ref  | Remote Repository Type | repo_layout_ref  | Virtual Repository Type | repo_layout_ref  | Federated Repository Type | repo_layout_ref  |
+-----------------------+------------------+------------------------+------------------+-------------------------+------------------+---------------------------+------------------+
| Alpine                | simple-default   | Alpine                 | simple-default   | Alpine                  | simple-default   | Alpine                    | simple-default   |
+-----------------------+------------------+------------------------+------------------+-------------------------+------------------+---------------------------+------------------+
| Bower                 | bower-default    | Bower                  | bower-default    | Bower                   | bower-default    | Bower                     | bower-default    |
+-----------------------+------------------+------------------------+------------------+-------------------------+------------------+---------------------------+------------------+
| CRAN                  | simple-default   | CRAN                   | simple-default   | CRAN                    | simple-default   | CRAN                      | simple-default   |
+-----------------------+------------------+------------------------+------------------+-------------------------+------------------+---------------------------+------------------+
| Cargo                 | simple-default   | Cargo                  | simple-default   |                         |                  | Cargo                     | simple-default   |
+-----------------------+------------------+------------------------+------------------+-------------------------+------------------+---------------------------+------------------+
| Chef                  | simple-default   | Chef                   | simple-default   | Chef                    | simple-default   | Chef                      | simple-default   |
+-----------------------+------------------+------------------------+------------------+-------------------------+------------------+---------------------------+------------------+
| CocoaPods             | simple-default   | CocoaPods              | simple-default   |                         |                  | CocoaPods                 | simple-default   |
+-----------------------+------------------+------------------------+------------------+-------------------------+------------------+---------------------------+------------------+
| Composer              | composer-default | Composer               | composer-default | Composer                | composer-default | Composer                  | composer-default |
+-----------------------+------------------+------------------------+------------------+-------------------------+------------------+---------------------------+------------------+
| Conan                 | conan-default    | Conan                  | conan-default    | Conan                   | conan-default    | Conan                     | conan-default    |
+-----------------------+------------------+------------------------+------------------+-------------------------+------------------+---------------------------+------------------+
| Conda                 | simple-default   | Conda                  | simple-default   | Conda                   | simple-default   | Conda                     | simple-default   |
+-----------------------+------------------+------------------------+------------------+-------------------------+------------------+---------------------------+------------------+
| Debian                | simple-default   | Debian                 | simple-default   | Debian                  | simple-default   | Debian                    | simple-default   |
+-----------------------+------------------+------------------------+------------------+-------------------------+------------------+---------------------------+------------------+
| Docker                | simple-default   | Docker                 | simple-default   | Docker                  | simple-default   | Docker                    | simple-default   |
+-----------------------+------------------+------------------------+------------------+-------------------------+------------------+---------------------------+------------------+
| Gems                  | simple-default   | Gems                   | simple-default   | Gems                    | simple-default   | Gems                      | simple-default   |
+-----------------------+------------------+------------------------+------------------+-------------------------+------------------+---------------------------+------------------+
| Generic               | simple-default   | Generic                | simple-default   | Generic                 | simple-default   | Generic                   | simple-default   |
+-----------------------+------------------+------------------------+------------------+-------------------------+------------------+---------------------------+------------------+
| GitLfs                | simple-default   | GitLfs                 | simple-default   | GitLfs                  | simple-default   | GitLfs                    | simple-default   |
+-----------------------+------------------+------------------------+------------------+-------------------------+------------------+---------------------------+------------------+
| Go                    | go-default       | Go                     | go-default       | Go                      | go-default       | Go                        | go-default       |
+-----------------------+------------------+------------------------+------------------+-------------------------+------------------+---------------------------+------------------+
| Gradle                | maven-2-default  | Gradle                 | maven-2-default  | Gradle                  | maven-2-default  | Gradle                    | maven-2-default  |
+-----------------------+------------------+------------------------+------------------+-------------------------+------------------+---------------------------+------------------+
| Helm                  | simple-default   | Helm                   | simple-default   | Helm                    | simple-default   | Helm                      | simple-default   |
+-----------------------+------------------+------------------------+------------------+-------------------------+------------------+---------------------------+------------------+
| Ivy                   | ivy-default      | Ivy                    | ivy-default      | Ivy                     | ivy-default      | Ivy                       | ivy-default      |
+-----------------------+------------------+------------------------+------------------+-------------------------+------------------+---------------------------+------------------+
| Maven                 | maven-2-default  | Maven                  | maven-2-default  | Maven                   | maven-2-default  | Maven                     | maven-2-default  |
+-----------------------+------------------+------------------------+------------------+-------------------------+------------------+---------------------------+------------------+
| Npm                   | npm-default      | Npm                    | npm-default      | Npm                     | npm-default      | Npm                       | npm-default      |
+-----------------------+------------------+------------------------+------------------+-------------------------+------------------+---------------------------+------------------+
| NuGet                 | nuget-default    | NuGet                  | nuget-default    | NuGet                   | nuget-default    | NuGet                     | nuget-default    |
+-----------------------+------------------+------------------------+------------------+-------------------------+------------------+---------------------------+------------------+
| Opkg                  | simple-default   | Opkg                   | simple-default   | Opkg                    | simple-default   | Opkg                      | simple-default   |
+-----------------------+------------------+------------------------+------------------+-------------------------+------------------+---------------------------+------------------+
|                       |                  | P2                     | simple-default   | P2                      | simple-default   |                           |                  |
+-----------------------+------------------+------------------------+------------------+-------------------------+------------------+---------------------------+------------------+
| Pub                   | simple-default   | Pub                    | simple-default   | Pub                     | simple-default   | Pub                       | simple-default   |
+-----------------------+------------------+------------------------+------------------+-------------------------+------------------+---------------------------+------------------+
| Puppet                | puppet-default   | Puppet                 | puppet-default   | Puppet                  | puppet-default   | Puppet                    | puppet-default   |
+-----------------------+------------------+------------------------+------------------+-------------------------+------------------+---------------------------+------------------+
| Pypi                  | simple-default   | Pypi                   | simple-default   | Pypi                    | simple-default   | Pypi                      | simple-default   |
+-----------------------+------------------+------------------------+------------------+-------------------------+------------------+---------------------------+------------------+
| SBT                   | sbt-default      | SBT                    | sbt-default      | SBT                     | sbt-default      | SBT                       | sbt-default      |
+-----------------------+------------------+------------------------+------------------+-------------------------+------------------+---------------------------+------------------+
| Vagrant               | simple-default   |                        |                  |                         |                  | Vagrant                   | simple-default   |
+-----------------------+------------------+------------------------+------------------+-------------------------+------------------+---------------------------+------------------+
|                       |                  | VCS                    | simple-default   |                         |                  |                           |                  |
+-----------------------+------------------+------------------------+------------------+-------------------------+------------------+---------------------------+------------------+
| Rpm                   | simple-default   | Rpm                    | simple-default   | Rpm                     | simple-default   | Rpm                       | simple-default   |
+-----------------------+------------------+------------------------+------------------+-------------------------+------------------+---------------------------+------------------+
```

File: pkg/artifactory/repositories.go (hunk 23 above)
Comment (dasmanas) [reply pkg/artifactory/repositories.go:1373]: `opts ...bool` has been introduced to handle optional parameter with default values. This has been introduced only to run test cases with random legitimate data of repo layout. The function has been used for functional & test code. It will return random value only if you pass true (specifically designed to handle test data).

```
func getDefaultLocalRepoLayoutRef(repoType string, opts ...bool) string
func getDefaultRemoteRepoLayoutRef(repoType string, opts ...bool) string
func getDefaultVirtualRepoLayoutRef(repoType string, opts ...bool) string
func getDefaultFederatedRepoLayoutRef(repoType string, opts ...bool) string
```

File: pkg/artifactory/repositories.go (hunk 18 above)
[the remark this answers is not in the document]
Comment (alexhung) [reply pkg/artifactory/repositories.go:1261]: Also `randBool()` is already written.

File: pkg/artifactory/repositories.go (hunk 14 above)
Comment (alexhung) [reply pkg/artifactory/repositories.go:655]: No, these aren't new. We added them a few weeks ago

File: pkg/artifactory/repositories.go (hunk 17 above)
Comment (alexhung) [reply pkg/artifactory/repositories.go:1253]: Or use `randBool()` 😄

File: pkg/artifactory/repositories.go (hunk 23 above)
Comment (alexhung) [reply pkg/artifactory/repositories.go:1373]: No test code in production please.

File: pkg/artifactory/resource_artifactory_local_alpine_repository.go (hunk 5 above)
Comment (dasmanas) [reply pkg/artifactory/resource_artifactory_local_alpine_repository.go:21]: It is part of the original code. Type declaration has been brought inside the function `resourceArtifactoryLocalAlpineRepository` as part of code clean up. Therefore showing as a change/commit.

File: pkg/artifactory/resource_artifactory_local_debian_repository.go (hunk 9 above)
Comment (dasmanas) [reply pkg/artifactory/resource_artifactory_local_debian_repository.go]: variable packageType used to replace litteral `debian` from all occurrences

File: pkg/artifactory/resource_artifactory_local_repository_test.go (hunk 4 above)
Comment (dasmanas) [reply pkg/artifactory/resource_artifactory_local_repository_test.go:669]: variable packageType used to replace literal `docker` from all occurrences

File: pkg/artifactory/repositories.go [hunk 25]
```diff
@@ -330,426 +332,533 @@ var repoTypesLikeGeneric = []string{
...
-		Optional: true,
-		Default:  false,
-	},
-	"xray_index": {
-		Type:        schema.TypeBool,
-		Optional:    true,
-		Default:     false,
+func getBaseLocalRepoSchema(packageType string) map[string]*schema.Schema {
+
+	var baseLocalRepoSchema = map[string]*schema.Schema{
```
[the remark this answers is not in the document]
Comment (dasmanas) [reply pkg/artifactory/repositories.go:337]: Improvement done for following functions
```
func getBaseLocalRepoSchema(packageType string) map[string]*schema.Schema
func getBaseRemoteRepoSchema(packageType string) map[string]*schema.Schema
func getBaseVirtualRepoSchema(packageType string) map[string]*schema.Schema
func getBaseFederatedRepoSchema(packageType string) map[string]*schema.Schema {
```

File: pkg/artifactory/resource_artifactory_local_alpine_repository.go (hunk 3 above)
Comment (dasmanas) [reply pkg/artifactory/resource_artifactory_local_alpine_repository.go]: Improved.
variable packageType used to replace literal `alpine` from all occurrences

File: pkg/artifactory/resource_artifactory_local_alpine_repository.go (hunk 1 above)
Comment (dasmanas) [reply pkg/artifactory/resource_artifactory_local_alpine_repository.go]: Improvement done. variable packageType used to replace literal `alpine` from all occurrences

File: pkg/artifactory/resource_artifactory_local_docker_repository.go (hunk 10 above)
Comment (dasmanas) [reply pkg/artifactory/resource_artifactory_local_docker_repository.go]: Improved. variable packageType used to replace literal `docker` from all occurrences

File: pkg/artifactory/resource_artifactory_local_repository_test.go (hunk 4 above)
Comment (dasmanas) [reply pkg/artifactory/resource_artifactory_local_repository_test.go:669]: Following 4 functions were implemented.
```
getDefaultLocalRepoLayoutRef
getDefaultFederatedRepoLayoutRef
getDefaultVirtualRepoLayoutRef
getDefaultRemoteRepoLayoutRef
```
As per the code **improvement**, all the above 4 functions has been removed from `repositories.go` file and a new function `func getDefaultRepoLayoutRef(repositoryType string, packageType string) string` has been implemented.

File: pkg/artifactory/repositories.go (hunk 15 above)
[the remark this answers is not in the document]
Comment (dasmanas) [reply pkg/artifactory/repositories.go:741]: Improvement done.
Function `func getDefaultRepoLayoutRef(repositoryType string, packageType string) string` in repositories.go. Using 
```
//Custom type
type DefaultRepoLayoutStruct struct {
	RepoLayoutRef      string
	SupportedRepoTypes map[string]bool
}

//master data
var defaultRepoLayoutMap = map[string]DefaultRepoLayoutStruct{
	"alpine":    {RepoLayoutRef: "simple-default", SupportedRepoTypes: map[string]bool{"local": true, "remote": true, "virtual": true, "federated": true}},
	"bower":     {RepoLayoutRef: "bower-default", SupportedRepoTypes: map[string]bool{"local": true, "remote": true, "virtual": true, "federated": true}},
...
```

File: pkg/artifactory/repositories.go [hunk 26]
```diff
@@ -1132,11 +1241,231 @@ func mkResourceSchema(skeema map[string]*schema.Schema, packer PackFunc, unpack
...
+			fmt.Printf("Option index is not defined. Index: %v, value: %v\n", i, val)
+		}
+	}
+	return selectRandomFlag
+}
+
+//Return the default repo layout of Local Repository type
+func getDefaultLocalRepoLayoutRef(repoType string, opts ...bool) string {
+
+	selectRandom := isSelectRandom(opts...)
```
[the remark this answers is not in the document]
Comment (dasmanas) [reply pkg/artifactory/repositories.go:1277]: As part of improvement `selectRandomFromMapOfStrings` and `isSelectRandom` functions has been removed. Function `getValidRandomDefaultRepoLayoutRef` has been created in resource_artifactory_local_repository_test.go file.

File: pkg/artifactory/repositories.go [hunk 27]
```diff
@@ -1132,11 +1241,231 @@ func mkResourceSchema(skeema map[string]*schema.Schema, packer PackFunc, unpack
...
 		},
 
-		Schema: skeema,
+		Schema:        skeema,
 		CustomizeDiff: projectEnvironmentsDiff,
 	}
 }
 
+//Returns random string from a map[string]string
+func selectRandomFromMapOfStrings(m map[string]string) string {
```
[the remark this answers is not in the document]
Comment (dasmanas) [reply pkg/artifactory/repositories.go:1250]: As part of improvement `selectRandomFromMapOfStrings` and `isSelectRandom` functions has been removed. Function `getValidRandomDefaultRepoLayoutRef` has been created in resource_artifactory_local_repository_test.go file.

File: pkg/artifactory/repositories.go (hunk 18 above)
[the remark this answers is not in the document]
Comment (dasmanas) [reply pkg/artifactory/repositories.go:1261]: As part of improvement `isSelectRandom` function has been removed. Function `getValidRandomDefaultRepoLayoutRef` has been created in resource_artifactory_local_repository_test.go file.

File: pkg/artifactory/repositories.go (hunk 19 above)
[the remark this answers is not in the document]
Comment (dasmanas) [reply pkg/artifactory/repositories.go:1275]: Improvement done. Similar code has been removed. 

Custom type
```
type DefaultRepoLayoutStruct struct {
	RepoLayoutRef      string
	SupportedRepoTypes map[string]bool
}
```

//Consolidated list of Default Repo Layout for all Package Types with active Repo Types
```
var defaultRepoLayoutMap = map[string]DefaultRepoLayoutStruct{
	"alpine":    {RepoLayoutRef: "simple-default", SupportedRepoTypes: map[string]bool{"local": true, "remote": true, "virtual": true, "federated": true}},
	"bower":     {RepoLayoutRef: "bower-default", SupportedRepoTypes: map[string]bool{"local": true, "remote": true, "virtual": true, "federated": true}},
}

...


```

File: pkg/artifactory/resource_artifactory_local_alpine_repository.go [hunk 28]
```diff
@@ -4,37 +4,39 @@ import (
...
-		Optional: true,
-		Description: "Used to sign index files in Alpine Linux repositories. " +
-			"See: https://www.jfrog.com/confluence/display/JFROG/Alpine+Linux+Repositories#AlpineLinuxRepositories-SigningAlpineLinuxIndex",
-	},
-}, compressionFormats)
-
 func resourceArtifactoryLocalAlpineRepository() *schema.Resource {
+	const pkt = "alpine"
+
+	var alpineLocalSchema = mergeSchema(getBaseLocalRepoSchema(pkt), map[string]*schema.Schema{
```
[the remark this answers is not in the document]
Comment (dasmanas) [reply pkg/artifactory/resource_artifactory_local_alpine_repository.go]: improvement done.
`const packageType = "alpine"`

File: pkg/artifactory/resource_artifactory_local_debian_repository.go (hunk 9 above)
[the remark this answers is not in the document]
Comment (dasmanas) [reply pkg/artifactory/resource_artifactory_local_debian_repository.go]: Done.

File: pkg/artifactory/resource_artifactory_local_alpine_repository.go (hunk 1 above)
Comment (dasmanas) [reply pkg/artifactory/resource_artifactory_local_alpine_repository.go]: Done

File: pkg/artifactory/resource_artifactory_local_alpine_repository.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (dasmanas) [reply pkg/artifactory/resource_artifactory_local_alpine_repository.go]: done

File: pkg/artifactory/resource_artifactory_local_repository_test.go (hunk 4 above)
Comment (dasmanas) [reply pkg/artifactory/resource_artifactory_local_repository_test.go]: Improved. Function `getDefaultLocalRepoLayoutRef` has been removed and new improvement has been built.

File: pkg/artifactory/resource_artifactory_remote_helm_repository.go (hunk 6 above)
Comment (dasmanas) [reply pkg/artifactory/resource_artifactory_remote_helm_repository.go]: variable packageType used to replace literal `helm` from all occurrences

File: pkg/artifactory/repositories.go [hunk 29]
```diff
@@ -1271,199 +1267,52 @@ func isSelectRandom(opts ...bool) bool {
...
-		repoLayout = selectRandomFromMapOfStrings(federatedDefaultRepoLayoutMap)
+//Return the default repo layout by Repository Type & Package Type
+func getDefaultRepoLayoutRef(repositoryType string, packageType string) string {
+	if defaultRepoLayoutMap[packageType].SupportedRepoTypes[repositoryType] == true {
+		return defaultRepoLayoutMap[packageType].RepoLayoutRef
 	} else {
-		if value, ok := federatedDefaultRepoLayoutMap[repoType]; ok {
-			repoLayout = value
-		}
+		panic(fmt.Errorf("Default Repo Layout not found for repository type: %s & package type: %s ", repositoryType, packageType))
```
Comment (alexhung) [inline pkg/artifactory/repositories.go:1314]: Please don't `panic` here. The func should return this as error so TF can handle it appropriately.

Take a look at the change @chb0github suggested here: https://github.com/jfrog/terraform-provider-artifactory/pull/335/files/886db2494e2d43ea749df6d132792b09b111c804..8b86d8aa22882e8c47f1271bbf2eb3c1f56d4f14#r814977949

File: pkg/artifactory/resource_artifactory_remote_repository_test.go (hunk 7 above)
Comment (dasmanas) [reply pkg/artifactory/resource_artifactory_remote_repository_test.go]: Commented code cleaned up.

File: pkg/artifactory/resource_artifactory_remote_repository_test.go (hunk 8 above)
Comment (dasmanas) [reply pkg/artifactory/resource_artifactory_remote_repository_test.go]: Done

File: pkg/artifactory/repositories.go (hunk 17 above)
Comment (dasmanas) [reply pkg/artifactory/repositories.go:1249]: Not applicable any more

File: pkg/artifactory/repositories.go [hunk 30]
```diff
@@ -1271,199 +1267,52 @@ func isSelectRandom(opts ...bool) bool {
...
-		repoLayout = selectRandomFromMapOfStrings(remoteDefaultRepoLayoutMap)
-	} else {
-		if value, ok := remoteDefaultRepoLayoutMap[repoType]; ok {
-			repoLayout = value
-		}
-	}
-	return repoLayout
+type DefaultRepoLayoutStruct struct {
+	RepoLayoutRef      string
+	SupportedRepoTypes map[string]bool
```
Comment (alexhung) [inline pkg/artifactory/repositories.go:1272]: Let's call this `SupportedRepoClasses`

File: pkg/artifactory/repositories.go (hunk 20 above)
Comment (dasmanas) [reply pkg/artifactory/repositories.go]: Code improved. Function `selectRandom` removed and not applicable any more. New function `func getValidRandomDefaultRepoLayoutRef()` in resource_artifactory_local_repository_test.go file

File: pkg/artifactory/repositories.go [hunk 31]
```diff
@@ -1271,199 +1267,52 @@ func isSelectRandom(opts ...bool) bool {
...
-		"sbt":       "sbt-default",
-		"vagrant":   "simple-default",
-		"rpm":       "simple-default",
-	}
-
-	if selectRandom {
-		repoLayout = selectRandomFromMapOfStrings(federatedDefaultRepoLayoutMap)
+//Return the default repo layout by Repository Type & Package Type
+func getDefaultRepoLayoutRef(repositoryType string, packageType string) string {
+	if defaultRepoLayoutMap[packageType].SupportedRepoTypes[repositoryType] == true {
```
Comment (alexhung) [inline pkg/artifactory/repositories.go:1311]: This is more Golang idiomatic:

```go
if v, ok := defaultRepoLayoutMap[packageType].SupportedRepoTypes[repositoryType]; ok && v {
    return defaultRepoLayoutMap[packageType].RepoLayoutRef
}
```

Also you should check for validity for both `packageType` and `repositoryType`.

File: pkg/artifactory/repositories.go [hunk 32]
```diff
@@ -1271,199 +1267,52 @@ func isSelectRandom(opts ...bool) bool {
...
-		"pypi":      "simple-default",
-		"sbt":       "sbt-default",
-		"vagrant":   "simple-default",
-		"rpm":       "simple-default",
-	}
-
-	if selectRandom {
-		repoLayout = selectRandomFromMapOfStrings(federatedDefaultRepoLayoutMap)
+//Return the default repo layout by Repository Type & Package Type
+func getDefaultRepoLayoutRef(repositoryType string, packageType string) string {
```
Comment (alexhung) [inline pkg/artifactory/repositories.go:1310]: Let's call it `repositoryClass` instead.

File: pkg/artifactory/repositories.go (hunk 22 above)
Comment (dasmanas) [reply pkg/artifactory/repositories.go]: Improved. new function is `getDefaultRepoLayoutRef`

File: pkg/artifactory/repositories.go [hunk 33]
```diff
@@ -1271,199 +1267,52 @@ func isSelectRandom(opts ...bool) bool {
...
-		repoLayout = selectRandomFromMapOfStrings(virtualDefaultRepoLayoutMap)
-	} else {
-		if value, ok := virtualDefaultRepoLayoutMap[repoType]; ok {
-			repoLayout = value
-		}
-	}
-	return repoLayout
+//Consolidated list of Default Repo Layout for all Package Types with active Repo Types
+var defaultRepoLayoutMap = map[string]DefaultRepoLayoutStruct{
+	"alpine":    {RepoLayoutRef: "simple-default", SupportedRepoTypes: map[string]bool{"local": true, "remote": true, "virtual": true, "federated": true}},
```
Comment (alexhung) [inline pkg/artifactory/repositories.go:1277]: There are no `false` value in the `SupportedRepoTypes` why not just a list of repo classes and then check if the requested class is in the list?

**Review by alexhung — CHANGES_REQUESTED** [review]

File: pkg/artifactory/resource_artifactory_local_generic_repository.go (hunk 2 above)
Comment (dasmanas) [reply pkg/artifactory/resource_artifactory_local_generic_repository.go:19]: probable existing issue fixed. Previously `inSchema(baseRemoteSchema)` has been changed to `inSchema(baseLocalRepoSchema)`. Using BaseLocalRepoSchema instead of BaseRemoteRepoSchema.

File: pkg/artifactory/resource_artifactory_remote_repository_test.go (hunk 11 above)
Comment (dasmanas) [reply pkg/artifactory/resource_artifactory_remote_repository_test.go:89]: `TestAccRemoteDockerRepositoryWithAdditionalCheckFunctions` is invoking separate function `mkRemoteTestCaseWithAdditionalCheckFunctions`. Where we are passing additional `addCheckFunctions`. Currently `mkNewRemoteTestCase` not providing the capability of additional check functions.

File: pkg/artifactory/resource_artifactory_virtual_maven_repository.go (hunk 13 above)
Comment (dasmanas) [reply pkg/artifactory/resource_artifactory_virtual_maven_repository.go:53]: improved.

File: pkg/artifactory/repositories.go (hunk 21 above)
Comment (dasmanas) [reply pkg/artifactory/repositories.go]: Good to know. For now as part of improvement `selectRandomFromMapOfStrings` has been removed.

File: pkg/artifactory/repositories.go (hunk 16 above)
Comment (dasmanas) [reply pkg/artifactory/repositories.go:822]: All the following functions have been removed to make the code clean.
```
getDefaultLocalRepoLayoutRef
getDefaultFederatedRepoLayoutRef
getDefaultVirtualRepoLayoutRef
getDefaultRemoteRepoLayoutRef
```
`getDefaultRepoLayoutRef` function has been implemented instead.

File: pkg/artifactory/repositories.go (hunk 29 above)
Comment (dasmanas) [reply pkg/artifactory/repositories.go:1314]: Implemented panic as per the suggestion https://github.com/jfrog/terraform-provider-artifactory/pull/335#discussion_r814986324

Comment (dasmanas) [reply pkg/artifactory/repositories.go:1314]: Improved as suggested. Introduced error. TF will handle it as required.
```
func getDefaultRepoLayoutRef(repositoryType string, packageType string) (string, error)
```

File: pkg/artifactory/repositories.go (hunk 30 above)
Comment (dasmanas) [reply pkg/artifactory/repositories.go:1272]: Renamed.

File: pkg/artifactory/repositories.go (hunk 31 above)
Comment (dasmanas) [reply pkg/artifactory/repositories.go:1311]: Improved.

File: pkg/artifactory/repositories.go (hunk 32 above)
Comment (dasmanas) [reply pkg/artifactory/repositories.go]: function `selectRandomFromMapOfStrings` has been removed.

File: pkg/artifactory/repositories.go (hunk 33 above)
Comment (dasmanas) [reply pkg/artifactory/repositories.go:1277]: Default is false. For a list I need to traverse and match every time. With current implementation it is a straight lookup by key.

File: pkg/artifactory/resource_artifactory_local_repository_test.go [hunk 34]
```diff
@@ -661,3 +662,56 @@ func TestAccLocalAllRepoTypes(t *testing.T) {
 		})
 	}
 }
+
+//Usage of the function is strictly restricted to Test Cases
+func getValidRandomDefaultRepoLayoutRef() string {
```
Comment (chb0github) [inline pkg/artifactory/resource_artifactory_local_repository_test.go:667]: There is already a function that does this : `randSelect` - util.go:126

File: pkg/artifactory/repositories.go [hunk 35]
```diff
@@ -330,442 +332,531 @@ var repoTypesLikeGeneric = []string{
...
+			Type:     schema.TypeString,
+			Optional: true,
+			Computed: true,Description: "List of artifact patterns to include when evaluating artifact requests in the form of x/y/**/z/*. When used, only artifacts matching one of the include patterns are served. By default, all artifacts are included (**/*).",
+		},
+		"excludes_pattern": {
+			Type:     schema.TypeString,
+			Optional: true,
+			Computed: true,
+		Description: "List of artifact patterns to exclude when evaluating artifact requests, in the form of x/y/**/z/*. By default no artifacts are excluded.",},
+		"repo_layout_ref": {
```
Comment (chb0github) [inline pkg/artifactory/repositories.go:383]: Having a whole function for this is kind of overkill - you can chain merges together

```go
skeema := mergeSchema(baseLocalRepo,repoLayout,whatever,whatever2)
```
The only difference is this one field and now there's a lot of changed lines.

File: pkg/artifactory/repositories.go (hunk 16 above)
Comment (chb0github) [reply pkg/artifactory/repositories.go:824]: please implement that function

File: pkg/artifactory/repositories.go [hunk 36]
```diff
@@ -1148,11 +1239,84 @@ func mkResourceSchema(skeema map[string]*schema.Schema, packer PackFunc, unpack
...
+	"vagrant":   {RepoLayoutRef: "simple-default", SupportedRepoTypes: map[string]bool{"local": true, "federated": true}},
+	"vcs":       {RepoLayoutRef: "simple-default", SupportedRepoTypes: map[string]bool{"remote": true}},
+	"rpm":       {RepoLayoutRef: "simple-default", SupportedRepoTypes: map[string]bool{"local": true, "remote": true, "virtual": true, "federated": true}},
+}
+
+//Return the default repo layout by Repository Type & Package Type
+func getDefaultRepoLayoutRef(repositoryType string, packageType string) (string, error) {
+	if v, ok := defaultRepoLayoutMap[packageType].SupportedRepoTypes[repositoryType]; ok && v {
+		return defaultRepoLayoutMap[packageType].RepoLayoutRef, nil
+	} else {
```
Comment (chb0github) [inline pkg/artifactory/repositories.go:1315]: You can completely delete the `else` here.  Keep the 2nd return, but since the `if` returns, the rest of the code is the `else`

**Review by chb0github — CHANGES_REQUESTED** [review]
Please implement `getDefaultRepoLayoutRef` as suggested so you don't have to C&P
```go
func getDefaultRepoLayoutRef(repositoryType string, packageType string) func() (interface{}, error) {
	return func() (interface{}, error) {
		if v, ok := defaultRepoLayoutMap[packageType].SupportedRepoTypes[repositoryType]; ok && v {
			return defaultRepoLayoutMap[packageType].RepoLayoutRef, nil
		}
		return "", fmt.Errorf("default repo layout not found for repository type %v & package type %v", repositoryType, packageType)
	}
}
```
and use like:
```go
DefaultFunc: getDefaultRepoLayoutRef("local", packageType),
```

Then, you need only merge in the schema instead of moving a bunch of code into a new function:
```go
		"repo_layout_ref": {
			Type:     schema.TypeString,
			Optional: true,
			DefaultFunc: getDefaultRepoLayoutRef("local", packageType),
			Description: "Repository layout key for the local repository",
		},
```

**Comment by chb0github** [comment]
This change is long overdue - Even RT Doesn't guide the user well

File: pkg/artifactory/resource_artifactory_local_repository_test.go (hunk 34 above)
Comment (dasmanas) [reply pkg/artifactory/resource_artifactory_local_repository_test.go:674]: Improved.
```
func getValidRandomDefaultRepoLayoutRef() string {
	return randSelect("simple-default", "bower-default", "composer-default", "conan-default", "go-default", "maven-2-default", "ivy-default", "npm-default", "nuget-default", "puppet-default", "sbt-default").(string)
}
```
moved the test specific code to util_test.go

File: pkg/artifactory/repositories.go (hunk 36 above)
Comment (dasmanas) [reply pkg/artifactory/repositories.go]: improved.

File: pkg/artifactory/repositories.go (hunk 16 above)
Comment (dasmanas) [reply pkg/artifactory/repositories.go:824]: made the improvement.

File: pkg/artifactory/repositories.go [hunk 37]
```diff
@@ -330,442 +332,523 @@ var repoTypesLikeGeneric = []string{
...
-		Type:        schema.TypeBool,
-		Optional:    true,
-		Description: "When set, you may view content such as HTML or Javadoc files directly from Artifactory.\nThis may not be safe and therefore requires strict content moderation to prevent malicious users from uploading content that may compromise security (e.g., cross-site scripting attacks).",
-	},
-	"download_direct": {
-		Type:        schema.TypeBool,
-		Optional:    true,
-		Description: "When set, download requests to this repository will redirect the client to download the artifact directly from the cloud storage provider. Available in Enterprise+ and Edge licenses only.",
-	},
+func getBaseLocalRepoSchema(packageType string) map[string]*schema.Schema {
```
Comment (chb0github) [inline pkg/artifactory/repositories.go:335]: You don't need this function at all - look at your implementation:

```go
return map[string]*schema.Schema{}
```
Just declare the map as
```go
var baseLocalRepoSchema = ...
```
and then in your merge function, merge in just the bit acount the default layout

File: pkg/artifactory/resource_artifactory_federated_generic_repository.go [hunk 38]
```diff
@@ -8,7 +8,8 @@ import (
 )
 
 func resourceArtifactoryFederatedGenericRepository(repoType string) *schema.Resource {
-	var federatedSchema = mergeSchema(baseLocalRepoSchema, map[string]*schema.Schema{
+
+	var federatedSchema = mergeSchema(getBaseFederatedRepoSchema(repoType), map[string]*schema.Schema{
```
Comment (chb0github) [inline pkg/artifactory/resource_artifactory_federated_generic_repository.go:12]: Right here you would have:

```go
layoutSchema := map[string]*schema.Schema {

}.  

var federatedSchema = mergSchema(baseLocalRepo,layoutSchema,...)
```

**Comment by chb0github** [comment]
So, @dasmanas what is the hold up on this PR? You now have merge conflicts

**Comment by dasmanas** [comment]
> So, @dasmanas what is the hold up on this PR? You now have merge conflicts

I need to make changes for the following comments
https://github.com/jfrog/terraform-provider-artifactory/pull/335#discussion_r814955338
https://github.com/jfrog/terraform-provider-artifactory/pull/335#discussion_r816341262
https://github.com/jfrog/terraform-provider-artifactory/pull/335#discussion_r817244481
and need to rebase the branch.

File: pkg/artifactory/resource_artifactory_remote_repository_test.go (hunk 12 above)
Comment (dasmanas) [reply pkg/artifactory/resource_artifactory_remote_repository_test.go]: This is an area where if you can have additional test cases
```
var addCheckFunctions = []resource.TestCheckFunc{
		resource.TestCheckResourceAttr(fqrn, "repo_layout_ref", func() string { r, _ := getDefaultRepoLayoutRef("remote", repoType)(); return r.(string) }()), //Check to ensure repository layout is set as per default even when it is not passed.
	}
```

beyond 
```
extraChecks := mapToTestChecks(fqrn, extraFields)
defaultChecks := mapToTestChecks(fqrn, allFields)
```

`getDefaultRepoLayoutRef` function simplified further

File: pkg/artifactory/repositories.go (hunk 35 above)
Comment (dasmanas) [reply pkg/artifactory/repositories.go:338]: Improved as suggested

File: pkg/artifactory/resource_artifactory_federated_generic_repository.go (hunk 38 above)
Comment (dasmanas) [reply pkg/artifactory/resource_artifactory_federated_generic_repository.go]: improved as suggested.

File: pkg/artifactory/validators.go [hunk 39]
```diff
@@ -477,6 +479,16 @@ var projectKeyValidator = validation.ToDiagFunc(
 	validation.StringMatch(regexp.MustCompile(`^[a-z0-9]{3,10}$`), "project_key must be 3 - 10 lowercase alphanumeric characters"),
 )
 
+func repoLayoutRefSchemaOverrideValidator(_ interface{}, _ cty.Path) diag.Diagnostics {
```
Comment (chb0github) [inline pkg/artifactory/validators.go:482]: more appropriate might be `alwaysFailValidator` - but I think this PR has been tortured enough

**Review by chb0github — DISMISSED** [review]

**Review by chb0github — APPROVED** [review]

**Review by chb0github — DISMISSED** [review]

File: pkg/artifactory/repositories.go (hunk 37 above)
Comment (dasmanas) [reply pkg/artifactory/repositories.go]: improved as suggested

**Review by chb0github — APPROVED** [review]

**Review by maheshjfrog — DISMISSED** [review]
