### PR TITLE
Potential fix for local repo state drift

### LINKED ISSUE #1186: Local Alpine and Debian repositories adding project_environments to diff, causing changes
**Describe the bug**
When running a plan against an already existing local Alpine and Debian repository, the diff is showing changes, where `project_environments` is going to be added. Even after applying, the diff doesn't change (ignore `keypair_ref` attribute, that is something I am trying to add)

Part of diff that shows Alpine
Image

Part of diff that shows Debian

Image

**Requirements for and issue**
- [x] A description of the bug
- [x] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). **If this is not supplied, this issue will likely be closed without any effort expended.**

```terraform
resource "artifactory_keypair" "some-keypairGPG1" {
  pair_name         = "some-keypair${random_id.randid.id}"
  pair_type         = "GPG"
  alias             = "foo-alias1"
  private_key       = file("samples/gpg.priv")
  public_key        = file("samples/gpg.pub")
  lifecycle {
    ignore_changes  = [
      private_key,
      passphrase,
    ]
  }
}

resource "artifactory_local_debian_repository" "my-debian-repo" {
  key                       = "my-debian-repo"
  primary_keypair_ref       = artifactory_keypair.some-keypairGPG1.pair_name
  index_compression_formats = ["bz2", "lzma", "xz"]
  trivial_layout            = true
  depends_on                = [artifactory_keypair.some-keypairGPG1]
}

resource "artifactory_keypair" "some-keypairRSA" {
  pair_name         = "some-keypair"
  pair_type         = "RSA"
  alias             = "foo-alias"
  private_key       = file("samples/rsa.priv")
  public_key        = file("samples/rsa.pub")
  lifecycle {
    ignore_changes  = [
      private_key,
      passphrase,
    ]
  }
}

resource "artifactory_local_alpine_repository" "terraform-local-test-alpine-repo-basic" {
  key                 = "terraform-local-test-alpine-repo-basic"
  primary_keypair_ref = artifactory_keypair.some-keypairRSA.pair_name

  depends_on          = [artifactory_keypair.some-keypairRSA]
}
```
- [x] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`: `7.98.13`
- [x] Your version of terraform: `1.98`
- [x] Your version of terraform provider: `12.8.3/12.8.4`

**Expected behavior**
- `project_environments` shouldn't ever appear in the diff when not being set

### PR DESCRIPTION
**Pull request by alexhung**
Fixes #1186, #1200

* I was finally able to replicate/reproduce this state drift issue locally. This fixes *should* fix this issue, or it may not.
* Fix the incorrect default values for `tag_retention` and `block_pushing_schema1` attributes for Docker v2 repository resource
* Move `cdn_redirect` attribute to local attributes for better backward compatibility with resources created pre-Plugin Framework.

### CODE REVIEW

**Comment by zamanmh1** [comment]
Just to note on my diff showing the Docker repo, I think the defaults were already correct as per the documentation: https://registry.terraform.io/providers/jfrog/artifactory/latest/docs/resources/local_docker_v2_repository

Apologies for the confusion there. That change can be reverted.

File: pkg/artifactory/datasource/repository/virtual/datasource_artifactory_virtual_repository_test.go [hunk 1]
```diff
@@ -270,14 +271,14 @@ func mkNewVirtualTestCase(packageType string, t *testing.T, extraFields map[stri
...
-				Check:            resource.ComposeTestCheckFunc(checks...),
-				ConfigPlanChecks: testutil.ConfigPlanChecks(""),
-				// ConfigPlanChecks: resource.ConfigPlanChecks{
-				// 	PostApplyPreRefresh: []plancheck.PlanCheck{
-				// 		plancheck.ExpectEmptyPlan(),
-				// 	},
-				// },
+				Config: config,
+				Check:  resource.ComposeTestCheckFunc(checks...),
+				// ConfigPlanChecks: testutil.ConfigPlanChecks(""),
```
Comment (danielmkn) [inline pkg/artifactory/datasource/repository/virtual/datasource_artifactory_virtual_repository_test.go:276]: Do we keep the commented-out code?

**Review by danielmkn — DISMISSED** [review]

File: pkg/artifactory/datasource/repository/virtual/datasource_artifactory_virtual_repository_test.go (hunk 1 above)
Comment (alexhung) [reply pkg/artifactory/datasource/repository/virtual/datasource_artifactory_virtual_repository_test.go:276]: Generally no, but I keep this so we can easily switch between the 2 different ways for checking plan diffs.

**Review by danielmkn — APPROVED** [review]
